### ISSUE TITLE
Aspect Ratio of Images on PostCards dont align with the size of the box

### ISSUE THREAD

**Issue by Cryptonex7** [Kide-Devs/Kide#22]
#Description
Aspect Ratio of Images on PostCards don't align with the size of the box - which creates an empty gray space in above and below the image. 

## Potential Solution
Add the same image behind the actual image and enlarge it to cover the entire box and blur the image. Just like this : https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.socialmediaexaminer.com%2F8-apps-instagram-stories%2F&psig=AOvVaw1btnhgO8Y8M2z9lWrj0cB-&ust=1601713926516000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKDRyMa_lewCFQAAAAAdAAAAABAG

## Supporting Images
![Screenshot_20201002-133912](https://user-images.githubusercontent.com/34197902/94903545-99c0ae80-04b7-11eb-8316-e6e1e0497be5.jpg)

**Comment by emem365** [comment]
>Add the same image behind the actual image and enlarge it to cover the entire box and blur the image.

Are you sure you dont just want the image to "Fill" the container? A small part of the image would be cut off but it would look a lot more clean.
Either way, could I maybe take up this issue and try fixing it for you?

Would like to hear your thoughts about the fill solution

**Comment by Cryptonex7** [comment]
Well, if you could do a normal fill - while keeping the existing features of loading animations and placeholders intact, then you could surely do that.

However, if for any reason you cannot achieve a "Fill", then you could go with the proposed solution.

Thanks @emem365 for your attempt - we would be awaiting your PR.

Happy HacktoberFest. :)

**Comment by emem365** [comment]
Created a PR #34 to fix the issue. Have a look and merge if you find it sufficient. happy to help :)

**Comment by Cryptonex7** [comment]
Sure @emem365 , we will make sure your PR gets reviewed within 7 days. Thanks for contributing to KIDE. 

We have more such issues coming up tomorrow - do check back to find more issues in your interest.

Regards,
Cryptonex7

**Comment by Cryptonex7** [comment]
Meanwhile, @emem365 , we have listed new issues for Hacktoberfest - you might want to go and check them out as well.
