### ISSUE TITLE
"Help and feedback" & "Privacy Policy" Buttons inside settings not working.

### ISSUE THREAD

**Issue by Cryptonex7** [Kide-Devs/Kide#24]
## Description
- The Help & Feedback feature is there on the side drawer - which is functional. However, the same button in the settings Page is not working. 
- And the Privacy policy button is totally non-functional.

## Potential Solution
- Copy the action that happens on pressing the Help and Feedback Button from the side drawer to the one in the settings page. 
- Remove the Privacy Policy Button (We dont have it ready yet - we will add it once we are done with the policy).

## Supporting Images
![Screenshot_20201002-141200](https://user-images.githubusercontent.com/34197902/94904698-4fd8c800-04b9-11eb-80f4-f05dbc9c4a93.jpg)

**Comment by anirudhbagri** [comment]
I don't see any action on "Help and Feedback" in the drawer button.

**Comment by emem365** [comment]
@anirudhbagri I was gonna take up this issue myself but since you're already on it.
Check out lines 227-267 in  [pages/HomePage/Home.dart](https://github.com/Kide-Devs/Kide/blob/master/lib/pages/HomePage/Home.dart)
```
                      ListTile(
                        leading: Icon(Icons.help),
                        title: Text('Help and Feedback'),
                        onTap: () {
                          showDialog(
                            context: context,
                            builder: (context) => AlertDialog(
                             ... //Some More code
                          );
                        },
                      ),
```

Just copy paste the whole thing or maybe you can declare the AlertDialog as a seperate widget and use it in both the places. Good Luck :)

**Comment by Cryptonex7** [comment]
@emem365 Thanks for helping @anirudhbagri out. 
This is an open issue and both of you can attempt the PR for this issue.

**Comment by Ayushi673** [comment]
Hi @Cryptonex7, since this is an open issue I've worked on it an I'm trying for a PR. Please have a look. I will make further improvements if required.

**Comment by Ayushi673** [comment]
Hi @Cryptonex7, since this is an open issue I've worked on it an I'm trying for a pull request. Please have a look. I will make further improvements, if required.

**Comment by Cryptonex7** [comment]
Sure @Ayushi673  , we will make sure your PR gets reviewed within 7 days. Thanks for contributing to KIDE. 

We have more such issues coming up tomorrow - do check back to find more issues in your interest.

Regards,
Cryptonex7

**Comment by Cryptonex7** [comment]
Meanwhile, @anirudhbagri, @Ayushi673, @emem365 , we have listed new issues for Hacktoberfest - you might want to go and check them out as well.
