### ISSUE TITLE
[BUG]: Email ID not clickable in About Us Page.

### ISSUE THREAD

**Issue by Cryptonex7** [Kide-Devs/Kide#25]
## **Describe the bug**
In the About Us section, the page asks the user to connect with the developers on their email ID. However, it should be clickable - which directly opens gmail (or any other mail client) for the purpose of sending an email.

## **To Reproduce**
1. Open the side drawer on the home page
2. Go to 'About Us'
3. Scroll down till the end
4. There you could see the email ID, which should be clickable.

## **Expected behavior**
A clickable email ID.

## **Potential Solution**
The Help and Feedback uses an email function - it could be linked to the email text too.

## **Screenshots**
![Screenshot_20201002-133539](https://user-images.githubusercontent.com/34197902/94922921-a86b8d80-04d8-11eb-9d2d-db517d4369d5.jpg)

**Comment by rrkas** [comment]
i am interested. i can implement this.
please assign this issue to me.

**Comment by Cryptonex7** [comment]
Hey @rrkas, we appreciate your gesture to contribute to the code.

Feel free to take up this issue - and we would be waiting for your PR.

Make sure to resync your fork - if you have already forked the repo - as we just pushed some recent changes in master.

**Comment by Cryptonex7** [comment]
## NOTE: Anyone else who wants to contribute to this issue would also be welcomed, Only the best PR would be approved and merged. 

Thanks.

**Comment by rrkas** [comment]
Please check pull request #31

**Comment by Cryptonex7** [comment]
Sure @rrkas , we will make sure your PR gets reviewed within 7 days. Thanks for contributing to KIDE. 

We have more such issues coming up tomorrow - do check back to find more issues in your interest.

Regards,
Cryptonex7

**Comment by Cryptonex7** [comment]
Meanwhile, @rrkas , we have listed new issues for Hacktoberfest - you might want to go and check them out as well.

**Comment by theRealKIDE** [comment]
closing as resolved by #31
