### ISSUE TITLE
[BUG]:Overflowing attendance chart graph from screen

### ISSUE THREAD

**Issue by NikhilCodes** [Kide-Devs/Kide#32]
The issue can be seen clearly from the below image.

Yeah, you guessed it. It the overflow to the right. If you think you can fix it, go right ahead.

<a href="https://ibb.co/JmR5HGv"><img src="https://i.ibb.co/TYBmt74/sssss.jpg" alt="sssss" border="0"></a><br /><a target='_blank' href='https://usefulwebtool.com/'>eng to viet</a><br />

**Comment by Cryptonex7** [comment]
Woah @NikhilCodes - that is some unrealistic Attendance! Is it real or fake?

**Comment by NikhilCodes** [comment]
> Woah @NikhilCodes - that is some unrealistic Attendance! Is it real or fake?

Real bruh. All I need is a network of pplz, who provide SITREP accordingly.

**Comment by rajnis09** [comment]
If the task is not completed and no one is doing this work, then I would like to work on it if you assign me.

**Comment by NikhilCodes** [comment]
@rajnis09 We appreciate your involvement in open-source.
Go ahead. It's not completed! 
Remember the best PR will be merged.

**Comment by rajnis09** [comment]
Thanks

**Comment by rajnis09** [comment]
> @rajnis09 We appreciate your involvement in open-source.
> Go ahead. It's not completed!
> Remember the best PR will be merged.

@NikhilCodes Can you provide me the test login details so that I can work into it?

**Comment by Cryptonex7** [comment]
@rajnis09,

I am afraid that we cannot provide you with credentials. This is the only issue which requires a student specifically studying in KIIT University, Bhubaneshwar, India.

There are a few ways to handle this situation:
- Submit the PR, and the reviewers can test it for you.
- If you have friends in KIIT, you might take their help.
- All the other issues in this repository are generic and could be taken up by anybody in the world.


We are sorry for the inconvenience, we understand, that we should've mentioned this issue as "KIIT only".

We request you to manage it this time, and We assure you that this will be taken care of in future.

**Comment by rajnis09** [comment]
> @rajnis09,
> 
> I am afraid that we cannot provide you with credentials. This is the only issue which requires a student specifically studying in KIIT University, Bhubaneshwar, India.
> 
> There are a few ways to handle this situation:
> 
> * Submit the PR, and the reviewers can test it for you.
> * If you have friends in KIIT, you might take their help.
> * All the other issues in this repository are generic and could be taken up by anybody in the world.
> 
> We are sorry for the inconvenience, we understand, that we should've mentioned this issue as "KIIT only".
> 
> We request you to manage it this time, and We assure you that this will be taken care of in future.

> No, issues, I'll do it.

**Comment by rajnis09** [comment]
I have done the work @NikhilCodes 

Please have a look at the pull request #43 

Thanks

**Comment by theRealKIDE** [comment]
Closing, as resolved by #43
