### ISSUE TITLE
[BUG]:contacts page bottom padding

### ISSUE THREAD

**Issue by sambitraze** [Kide-Devs/Kide#38]
## **Describe the bug**
content in contacts page gets overlapped by bottom nav bar

## **Screenshots**

![Screenshot_1601667088](https://user-images.githubusercontent.com/23294656/94963030-17ff6e00-0515-11eb-8a2d-fdfdf662a8e8.png)

**Comment by parjanyaacoder** [comment]
I would like to work on this issue. Please assign.

**Comment by Cryptonex7** [comment]
Sure @parjanyaacoder we would love to have you contributing to Kide.
We will be awaiting your PR.

**Comment by ibrahimbroachwala** [comment]
I got this!

**Comment by Cryptonex7** [comment]
Sure @ibrahimbroachwala  , we will make sure your PR gets reviewed within 7 days. Thanks for contributing to KIDE.

Meanwhile, we have listed new issues for #Hacktoberfest - you might want to go and check them out as well.

Regards,
Cryptonex7

**Comment by vanshBhatia-A4k9** [comment]
Hey @sambitraze, can you please give a brief description of how to recreate this bug? It seems to work fine on my screen on the default settings?

**Comment by sambitraze** [comment]
> Hey @sambitraze, can you please give a brief description of how to recreate this bug? It seems to work fine on my screen on the default settings?

if u scroll down in the contact page  u will see some.part of the gridview gets hidden under the nav bar this issue is for devices with screen size 5 inch or less so just fix the spacing issue
